# Generated by Django 6.0.5 on 2026-05-11 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('students', '0002_student_cgpa_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_account', to='students.student'),
        ),
    ]
