# Generated by Django 6.0.5 on 2026-05-13 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_linked_student_alter_user_role'),
        ('accounts', '0002_user_student'),
    ]

    operations = [
    ]
