# Generated by Django 5.0.6 on 2026-05-14 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_linked_student_alter_user_role'),
        ('accounts', '0002_user_student'),
    ]

    operations = [
    ]
