# Generated by Django 5.2.14 on 2026-05-15 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_merge_20260514_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='student',
        ),
    ]
