# Generated by Django 6.0.5 on 2026-05-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_merge_20260513_0730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='linked_student',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('student', 'Student'), ('faculty', 'Faculty')], default='admin', max_length=20),
        ),
    ]
