# Generated by Django 6.0.4 on 2026-05-19 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_merge_20260519_0618'),
        ('students', '0006_merge_20260519_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='linked_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_accounts', to='students.student'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('student', 'Student'), ('faculty', 'Faculty'), ('parent', 'Parent')], default='admin', max_length=20),
        ),
    ]
