# Generated by Django 6.0.4 on 2026-05-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_linked_student_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('student', 'Student'), ('faculty', 'Faculty'), ('hr', 'HR'), ('accountant', 'Accountant'), ('librarian', 'Librarian'), ('hostel_warden', 'Hostel Warden'), ('placement_officer', 'Placement Officer'), ('transport_incharge', 'Transport Incharge'), ('alumni_coordinator', 'Alumni Coordinator'), ('parent', 'Parent')], default='admin', max_length=30),
        ),
    ]
