# Generated by Django 6.0.5 on 2026-05-12 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_cgpa_attendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='roll_number',
            new_name='register_number',
        ),
    ]
