# Generated by Django 5.2.14 on 2026-05-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_rename_roll_number_student_register_number'),
    ]

    def populate_roll_number(apps, schema_editor):
        Student = apps.get_model('students', 'Student')
        for student in Student.objects.all():
            if not student.roll_number:
                student.roll_number = str(student.id)
                student.save()

    operations = [
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='roll_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.RunPython(populate_roll_number, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='register_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
