# Generated by Django 6.0.5 on 2026-05-19 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_department_student_roll_number_and_more'),
        ('students', '0005_student_photo'),
    ]

    operations = [
    ]
