# Generated by Django 5.2.15 on 2026-06-29 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_merge_20260519_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='residence_type',
            field=models.CharField(choices=[('day_scholar', 'Day Scholar'), ('hosteler', 'Hosteler')], default='day_scholar', max_length=20),
        ),
    ]
