# Generated by Django 5.2.15 on 2026-07-03 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_student_aadhar_id_student_bank_account_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='bank_account_details',
        ),
        migrations.AddField(
            model_name='student',
            name='bank_account_holder_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='bank_account_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='bank_account_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='bank_branch_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='bank_ifsc_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
