# Generated by Django 6.0.5 on 2026-05-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='course',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
