# Generated by Django 5.2.15 on 2026-06-30 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='target',
            field=models.CharField(choices=[('all', 'All'), ('students', 'Students'), ('faculty', 'Faculty'), ('staff', 'Staff'), ('admin', 'Admin'), ('parents', 'Parents')], default='all', max_length=20),
        ),
    ]
