with open('students/views.py', 'r') as f:
    lines = f.readlines()

new_lines = lines[:76]

new_lines.extend([
    "    def get_object(self):\n",
    "        obj = super().get_object()\n",
    "        user = self.request.user\n",
    "        if user.role == 'student' and user.linked_student_id != obj.id:\n",
    "            raise PermissionDenied('You can only view your own profile.')\n",
    "        if user.role == 'faculty' and obj.department != user.department:\n",
    "            raise PermissionDenied('You can only manage students in your department.')\n",
    "        return obj\n",
    "\n",
    "from django.http import HttpResponse\n",
    "from rest_framework.views import APIView\n",
    "from rest_framework.response import Response\n",
    "from rest_framework.parsers import MultiPartParser\n",
    "from rest_framework.permissions import AllowAny\n",
    "import openpyxl\n",
    "\n",
    "class StudentBulkUploadSampleView(APIView):\n",
    "    permission_classes = [AllowAny]\n",
    "\n",
    "    def get(self, request):\n",
    "        wb = openpyxl.Workbook()\n",
    "        ws = wb.active\n",
    "        ws.title = \"Students\"\n",
    "\n",
    "        headers = ['First Name', 'Last Name', 'Email', 'Phone', 'Register Number', 'Department', 'Course', 'Year', 'Gender']\n",
    "        ws.append(headers)\n",
    "\n",
    "        example = ['John', 'Doe', 'john.doe@example.com', '1234567890', 'REG001', 'Computer Science', 'B.Tech - Computer Science & Engineering', 1, 'male']\n",
    "        ws.append(example)\n",
    "\n",
    "        response = HttpResponse(content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')\n",
    "        response['Content-Disposition'] = 'attachment; filename=student_bulk_upload_sample.xlsx'\n",
    "        wb.save(response)\n",
    "        return response\n",
    "\n",
    "class StudentBulkUploadView(APIView):\n",
    "    permission_classes = [IsAdminOrFaculty]\n",
    "    parser_classes = [MultiPartParser]\n",
    "\n",
    "    def post(self, request):\n",
    "        file_obj = request.FILES.get('file')\n",
    "        if not file_obj:\n",
    "            return Response({'error': 'No file uploaded'}, status=400)\n",
    "            \n",
    "        if not file_obj.name.endswith('.xlsx'):\n",
    "            return Response({'error': 'Only .xlsx files are supported'}, status=400)\n",
    "\n",
    "        try:\n",
    "            wb = openpyxl.load_workbook(file_obj)\n",
    "            ws = wb.active\n",
    "        except Exception as e:\n",
    "            return Response({'error': f'Failed to parse excel file: {str(e)}'}, status=400)\n",
    "\n",
    "        errors = []\n",
    "        created_count = 0\n",
    "        \n",
    "        user = request.user\n",
    "        enforced_dept = user.department if user.role == 'faculty' else None\n",
    "\n",
    "        for row_idx, row in enumerate(ws.iter_rows(values_only=True), start=1):\n",
    "            if row_idx <= 2:\n",
    "                continue\n",
    "                \n",
    "            if all(cell is None or str(cell).strip() == '' for cell in row):\n",
    "                continue\n",
    "                \n",
    "            try:\n",
    "                first_name = str(row[0]).strip() if row[0] else ''\n",
    "                last_name = str(row[1]).strip() if row[1] else ''\n",
    "                email = str(row[2]).strip() if row[2] else ''\n",
    "                phone = str(row[3]).strip() if row[3] else ''\n",
    "                register_number = str(row[4]).strip() if row[4] else ''\n",
    "                department = str(row[5]).strip() if row[5] else ''\n",
    "                course = str(row[6]).strip() if row[6] else ''\n",
    "                year = row[7]\n",
    "                gender = str(row[8]).strip().lower() if row[8] else 'other'\n",
    "\n",
    "                if not first_name or not email or not register_number or not department or not course or not year:\n",
    "                    errors.append(f\"Row {row_idx}: Missing required fields (First Name, Email, Register Number, Department, Course, Year).\")\n",
    "                    continue\n",
    "                    \n",
    "                if enforced_dept and department.lower() != enforced_dept.lower():\n",
    "                    errors.append(f\"Row {row_idx}: You can only add students to your own department ({enforced_dept}).\")\n",
    "                    continue\n",
    "\n",
    "                if Student.objects.filter(email=email).exists():\n",
    "                    errors.append(f\"Row {row_idx}: Email '{email}' already exists.\")\n",
    "                    continue\n",
    "                    \n",
    "                if Student.objects.filter(register_number=register_number).exists() or Student.objects.filter(roll_number=register_number).exists():\n",
    "                    errors.append(f\"Row {row_idx}: Register Number '{register_number}' already exists.\")\n",
    "                    continue\n",
    "                    \n",
    "                try:\n",
    "                    year_int = int(year)\n",
    "                except ValueError:\n",
    "                    errors.append(f\"Row {row_idx}: Year must be a number.\")\n",
    "                    continue\n",
    "                    \n",
    "                if gender not in ['male', 'female', 'other']:\n",
    "                    gender = 'other'\n",
    "\n",
    "                student = Student(\n",
    "                    first_name=first_name,\n",
    "                    last_name=last_name,\n",
    "                    email=email,\n",
    "                    phone=phone,\n",
    "                    register_number=register_number,\n",
    "                    roll_number=register_number,\n",
    "                    department=department,\n",
    "                    course=course,\n",
    "                    year=year_int,\n",
    "                    gender=gender\n",
    "                )\n",
    "                student.save()\n",
    "                created_count += 1\n",
    "                \n",
    "            except Exception as e:\n",
    "                errors.append(f\"Row {row_idx}: Unexpected error: {str(e)}\")\n",
    "\n",
    "        return Response({\n",
    "            'success': True,\n",
    "            'created_count': created_count,\n",
    "            'errors': errors\n",
    "        })\n",
])

with open('students/views.py', 'w') as f:
    f.writelines(new_lines)
