# Generated by Django 6.0.4 on 2026-05-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_employee_address_employee_basic_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='half_day',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payroll',
            name='hra_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='payroll',
            name='pf_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='payroll',
            name='ta_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='payroll',
            name='tax_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
