# Generated by Django 6.0.4 on 2026-05-22 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_faculty_course'),
        ('hr', '0003_payroll_half_day_payroll_hra_pct_payroll_pf_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='faculty',
            field=models.OneToOneField(blank=True, help_text='Linked faculty record (auto-populated on sync)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_employee', to='faculty.faculty'),
        ),
    ]
