# Generated by Django 6.0.4 on 2026-05-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('semester', models.PositiveIntegerField(default=1)),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday')], max_length=15)),
                ('period', models.PositiveIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('subject', models.CharField(max_length=200)),
                ('subject_code', models.CharField(blank=True, max_length=20)),
                ('faculty_name', models.CharField(blank=True, max_length=200)),
                ('room', models.CharField(blank=True, max_length=50)),
                ('academic_year', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'ordering': ['day', 'period'],
                'unique_together': {('course', 'semester', 'day', 'period', 'academic_year')},
            },
        ),
    ]
