# Generated by Django 6.0.4 on 2026-05-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_feestructure_finerule_scholarship_fee_academic_year_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FineRule',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='student',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='scholarship',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='fine_amount',
        ),
        migrations.AlterField(
            model_name='fee',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('overdue', 'Overdue')], default='pending', max_length=10),
        ),
        migrations.DeleteModel(
            name='Installment',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Scholarship',
        ),
    ]
