# Generated by Django 6.0.4 on 2026-05-22 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0006_merge_20260519_0618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('exam_type', models.CharField(choices=[('internal', 'Internal'), ('external', 'External'), ('practical', 'Practical'), ('viva', 'Viva')], default='internal', max_length=20)),
                ('course', models.CharField(max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('semester', models.PositiveIntegerField(default=1)),
                ('subject', models.CharField(max_length=200)),
                ('subject_code', models.CharField(blank=True, max_length=20)),
                ('exam_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('room', models.CharField(blank=True, max_length=50)),
                ('max_marks', models.PositiveIntegerField(default=100)),
                ('pass_marks', models.PositiveIntegerField(default=40)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('academic_year', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('grade', models.CharField(blank=True, choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C', 'C'), ('F', 'F'), ('AB', 'AB')], max_length=5)),
                ('is_pass', models.BooleanField(default=False)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('entered_by', models.CharField(blank=True, max_length=100)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='examination.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='students.student')),
            ],
            options={
                'unique_together': {('exam', 'student')},
            },
        ),
    ]
